name: Translations Sync

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.CI_SSH_KEY }}
          ssh-strict: false
          persist-credentials: true
      - name: Run lupdate
        uses: liri-infra/lupdate-action@master
      - name: Push sources and pull translations
        uses: liri-infra/transifex-action@master
            tx_token: ${{ secrets.TX_TOKEN }}
            committer_name: Liri CI
            committer_email: ci@liri.io
            master_branch: develop
            translations_folder: translations
            pull_translations: true
            push_sources: true
